CREATE TABLE invoice (
	code BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	price DECIMAL(10,2) NOT NULL,
	description VARCHAR(500),
	type VARCHAR(20) NOT NULL,
	date_release DATE NOT NULL,
	registration DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;